POST http://localhost:3000/auth/register 
Content-Type: application/json

{
"email": "bond@email.com", 
"password": "verysecret123",
"full_name": "James Bond"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "bond@email.com", 
"password": "verysecret123"
}

### 

GET http://localhost:3000/groups

###
POST http://localhost:3000/groups
Content-Type: application/json

{
"name": "Test savings"
}
###

GET http://localhost:3000/bills/2
###

POST http://localhost:3000/bills
Content-Type: application/json

{
"group_id": 2,
"amount": "1 Eur",
"description": "Test Tests"
}
###