POST http://localhost:3000/auth/register 
Content-Type: application/json

{
"email": "dov@email.com", 
"password": "dov",
"full_name": "dov zem"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "dov@gmail.com", 
"password": "dov"
}

### 

GET http://localhost:3000/groups

###
POST http://localhost:3000/groups
Content-Type: application/json

{
"name": "Money spenders"
}
###

GET http://localhost:3000/bills/2
###

POST http://localhost:3000/bills
Content-Type: application/json

{
"group_id": 2,
"amount": "1 Eur",
"description": "Test Tests"
}
###